name: Docs
on:
  push:
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
      # referenced external files
      - 'CHANGELOG.md'
jobs:
  job_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: python -m pip install -U pip wheel
      - run: |
          cd docs/
          pip install -r requirements.txt
          mkdocs build
  job_deploy:
    # deploy only on the "stable" branch
    if: ${{ github.ref == 'refs/heads/stable' }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: python -m pip install -U pip wheel
      - run: |
          cd docs/
          pip install -r requirements.txt
          mkdocs gh-deploy --force
